### ISSUE TITLE
转换不成功

### ISSUE THREAD

**Issue by yanlei2017** [yinzhedfs/swf2pdf#2]
ubuntu 16.04 ，tmp文件夹中有单页的png，但是转换完后pdffile文件夹中还是swf文件

**Comment by yinzhedfs** [comment]
这个可以看看日志里有什么异常或直接在脚本里调试下看看，因为转换图片和合并pdf这两步都不能保证百分百没问题，有可能就会导致后面步骤的异常，这两个程序都是来自外部的开源软件，调试下看是不是这两个程序的问题，有问题的话试试升级下这两个软件
